<a href="https://colab.research.google.com/github/Jingxian12/movie-recommender-system/blob/main/Movie_Recommender_System_(PART_A)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <div align =center > **TITLE : MOVIE RECOMMENDER SYSTEM**</div>

# **PART A : ETL**

**Summary:** I perform data preprocessing by integrating the `MovieLens` dataset with the `TMDB` dataset from **Kaggle**. For movies rated by users in MovieLens that are missing or incomplete in the Kaggle TMDB dataset, I use the **TMDB API** to extract the required missing metadata, ensuring a more complete and enriched movie information dataset to improve data completeness and support more effective recommendation modelling for our recommendation system later.

## **DATA ACQUISITION**

### - Import Necessary Libraries

In [ ]:
import pandas as pd
import numpy as np
import ast
import requests
import time
import json

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

We have 2 datasets to upload, which are MovieLens and TMDB Dataset

- `MovieLens` is for **Collaborative Filtering**
- `TMDB` is for **Content Based Filtering** and **NLP Based Filtering**

P.S. some of the tmdbId in `link.csv` have been modify myself because some movie have been removal or change the path in TMDB website(https://www.themoviedb.org/)

## **MovieLens**

In [ ]:
movies = pd.read_csv("/content/drive/MyDrive/dataset/movie/movieLens/movies.csv")
ratings = pd.read_csv("/content/drive/MyDrive/dataset/movie/movieLens/ratings.csv")
links = pd.read_csv("/content/drive/MyDrive/dataset/movie/movieLens/links.csv")

In [ ]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
links.head()

   movieId  imdbId  tmdbId media_type
0        1  114709     862      movie
1        2  113497    8844      movie
2        3  113228   15602      movie
3        4  114885   31357      movie
4        5  113041   11862      movie

In [ ]:
movieLens = pd.merge(
    movies,
    links,
    on="movieId",
    how="inner"
)

In [ ]:
movieLens.head()

,movieId,title,genres,imdbId,tmdbId,media_type
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862,movie
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,8844,movie
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,15602,movie
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,31357,movie
4,5,Father of the Bride Part II (1995),Comedy,113041,11862,movie

Let's check for duplicate rows in the `movieLens` DataFrame based on the `tmdbId` column.

In [ ]:
# Check column duplicated
duplicate_tmdb_ids_rows = movieLens[movieLens.duplicated(subset=['tmdbId','media_type'], keep=False)].sort_values('title')
display(duplicate_tmdb_ids_rows)

print(f"Number of duplicate rows based on 'tmdbId': {len(duplicate_tmdb_ids_rows)}")

,movieId,title,genres,imdbId,tmdbId,media_type
4169,6003,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Thriller,290538,4912,movie
9106,144606,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Romance|Thriller,270288,4912,movie
5854,32600,Eros (2004),Drama,377059,39850,movie
9135,147002,Eros (2004),Drama|Romance,343663,39850,movie
2141,2851,Saturn 3 (1980),Adventure|Sci-Fi|Thriller,81454,19761,movie
9468,168358,Saturn 3 (1980),Sci-Fi|Thriller,79285,19761,movie

Number of duplicate rows based on 'tmdbId': 6

I manually checked the **IDs** and noticed that these three movies are duplicates because **newer versions were updated** in the MovieLens dataset, so I kept the rows with the correct `MovieLens IDs (movieId)`,`IMDb IDs (imdbId)`,  and `TMDb IDs (tmdbId)`.

In [ ]:
movie_ids_to_remove = [6003, 32600, 2851]
movieLens = movieLens[~movieLens['movieId'].isin(movie_ids_to_remove)] # ~ means NOT

print(f"Updated movieLens DataFrame shape: {movieLens.shape}")

Updated movieLens DataFrame shape: (9739, 6)

At the same time, I standardized the ratings data by mapping duplicate MovieLens movie IDs to their correct movie IDs, ensuring all ratings for the same movie are consolidated under a single consistent identifier.

In [ ]:
movie_id_mapping = {
    6003: 144606,
    32600: 147002,
    2851: 168358
}

ratings['movieId'] = ratings['movieId'].replace(movie_id_mapping)

print("Movie IDs in ratings DataFrame have been standardized.")

Movie IDs in ratings DataFrame have been standardized.

In [ ]:
# Verify by checking the counts of these movie IDs or sampling the ratings DataFrame
print(ratings[ratings['movieId'].isin([6003,32600, 2851])].head())

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

In [ ]:
ratings.shape

(100836, 4)

## **TMDB Dataset**

In [ ]:
tmdb_movies = pd.read_csv("/content/drive/MyDrive/dataset/movie/tmdb/tmdb_5000_movies.csv")
tmdb_credits = pd.read_csv("/content/drive/MyDrive/dataset/movie/tmdb/tmdb_5000_credits.csv")

In [ ]:
tmdb = tmdb_movies.merge(
    tmdb_credits,
    left_on="id",
    right_on="movie_id",
)

In [ ]:
tmdb.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
tmdb.shape

(4803, 24)

In [ ]:
tmdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title_x               4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  movie_id              4803 non-null   int64
 21  title_y               4803 non-null   object
 22  cast                  4803 non-null   object
 23  crew                  4803 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [ ]:
tmdb =tmdb[['movie_id','title_x','genres','keywords','original_language','overview','production_companies','release_date','runtime','popularity','vote_average','vote_count','cast','crew']]

In [ ]:
tmdb.head()

,movie_id,title_x,genres,keywords,original_language,overview,production_companies,release_date,runtime,popularity,vote_average,vote_count,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,"In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,162.0,150.437577,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,"Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,169.0,139.082615,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,148.0,107.376788,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,165.0,112.312950,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,"John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,132.0,43.926995,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
print(tmdb.shape)
print(tmdb.info())

(4803, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              4803 non-null   int64
 1   title_x               4803 non-null   object
 2   genres                4803 non-null   object
 3   keywords              4803 non-null   object
 4   original_language     4803 non-null   object
 5   overview              4800 non-null   object
 6   production_companies  4803 non-null   object
 7   release_date          4802 non-null   object
 8   runtime               4801 non-null   float64
 9   popularity            4803 non-null   float64
 10  vote_average          4803 non-null   float64
 11  vote_count            4803 non-null   int64
 12  cast                  4803 non-null   object
 13  crew                  4803 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 525.5+ KB
None

### **- Check Missing Values**

In [ ]:
tmdb.isnull().sum()

movie_id                0
title_x                 0
genres                  0
keywords                0
original_language       0
overview                3
production_companies    0
release_date            1
runtime                 2
popularity              0
vote_average            0
vote_count              0
cast                    0
crew                    0
dtype: int64

In [ ]:
missing_info = tmdb[tmdb.isnull().any(axis=1)]
missing_info

,movie_id,title_x,genres,keywords,original_language,overview,production_companies,release_date,runtime,popularity,vote_average,vote_count,cast,crew
2656,370980,Chiamatemi Francesco - Il Papa della gente,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 717, ""name"": ""pope""}, {""id"": 5565, ""na...",it,NaN,"[{""name"": ""Taodue Film"", ""id"": 45724}]",2015-12-03,NaN,0.738646,7.3,12,"[{""cast_id"": 5, ""character"": ""Jorge Mario Berg...","[{""credit_id"": ""5660019ac3a36875f100252b"", ""de..."
4140,459488,"To Be Frank, Sinatra at 100","[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 6027, ""name"": ""music""}, {""id"": 225822,...",en,NaN,"[{""name"": ""Eyeline Entertainment"", ""id"": 60343}]",2015-12-12,NaN,0.050625,0.0,0,"[{""cast_id"": 0, ""character"": ""Narrator"", ""cred...","[{""credit_id"": ""592b25e4c3a368783e065a2f"", ""de..."
4431,292539,Food Chains,"[{""id"": 99, ""name"": ""Documentary""}]",[],de,NaN,[],2014-04-26,83.0,0.795698,7.4,8,[],"[{""credit_id"": ""5470c3b1c3a368085e000abd"", ""de..."
4553,380097,America Is Still the Place,[],[],en,1971 post civil rights San Francisco seemed li...,[],NaN,0.0,0.000000,0.0,0,[],[]

In [ ]:
tmdb = tmdb.dropna()
tmdb.shape

(4799, 14)

I removed rows with missing values from this dataset `(TMDb 5000 Movie Dataset from Kaggle)` because the dataset **might not fully match the movies rated by users in the MovieLens dataset**,

If the removed movies are useful for users, more **comprehensive information** can still be retrieved through the `TMDB API`.

### **- Preprocessing for TMDB dataset**

In [ ]:
tmdb.head()

,movie_id,title_x,genres,keywords,original_language,overview,production_companies,release_date,runtime,popularity,vote_average,vote_count,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,"In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,162.0,150.437577,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,"Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,169.0,139.082615,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,148.0,107.376788,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,165.0,112.312950,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,"John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,132.0,43.926995,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

From the dataframe, several columns such as `genres`, `keywords`, `production_companies`, `cast`, and `crew` are **stored as nested list/dictionary structures**, so I will standardize these fields by extracting only the key values to make the data more consistent and readable.

In [ ]:
# General converter(to get name from list)
def converter(x):
    if isinstance(x, str):
        x = ast.literal_eval(x)

    return [i["name"] for i in x] if x else []

#### Genres

In [ ]:
tmdb['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
tmdb["genres"] = tmdb["genres"].apply(converter)

In [ ]:
tmdb['genres'].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

#### Keywords

In [ ]:
tmdb['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [ ]:
tmdb["keywords"] = tmdb["keywords"].apply(converter)

In [ ]:
tmdb['keywords'].head()

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

#### Production Comapnies

In [ ]:
tmdb['production_companies'][0]

'[{"name": "Ingenious Film Partners", "id": 289}, {"name": "Twentieth Century Fox Film Corporation", "id": 306}, {"name": "Dune Entertainment", "id": 444}, {"name": "Lightstorm Entertainment", "id": 574}]'

In [ ]:
tmdb["production_companies"] = tmdb["production_companies"].apply(converter)

In [ ]:
tmdb['production_companies'].head()

0    [Ingenious Film Partners, Twentieth Century Fo...
1    [Walt Disney Pictures, Jerry Bruckheimer Films...
2                     [Columbia Pictures, Danjaq, B24]
3    [Legendary Pictures, Warner Bros., DC Entertai...
4                               [Walt Disney Pictures]
Name: production_companies, dtype: object

#### Cast

In [ ]:
def extract_cast_info(cast):
    if isinstance(cast, str):
        cast = ast.literal_eval(cast)

    cast_info = [
        {
            "character": c.get("character"),
            "name": c.get("name")
        }
        for c in cast
    ]

    return cast_info

In [ ]:
tmdb['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [ ]:
tmdb["cast"] = tmdb["cast"].apply(extract_cast_info)

In [ ]:
tmdb["cast"].head()

0    [{'character': 'Jake Sully', 'name': 'Sam Wort...
1    [{'character': 'Captain Jack Sparrow', 'name':...
2    [{'character': 'James Bond', 'name': 'Daniel C...
3    [{'character': 'Bruce Wayne / Batman', 'name':...
4    [{'character': 'John Carter', 'name': 'Taylor ...
Name: cast, dtype: object

#### Crew

In [ ]:
def extract_director(crew):
    if isinstance(crew, str):
        crew = ast.literal_eval(crew)

    directors = [c["name"] for c in crew if c.get("job") == "Director"]
    return directors

In [ ]:
tmdb['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [ ]:
tmdb["director"] = tmdb["crew"].apply(extract_director)

In [ ]:
tmdb['director'].head()

0        [James Cameron]
1       [Gore Verbinski]
2           [Sam Mendes]
3    [Christopher Nolan]
4       [Andrew Stanton]
Name: director, dtype: object

### **- Final TMDB Dataset**

In [ ]:
tmdb.head()

,movie_id,title_x,genres,keywords,original_language,overview,production_companies,release_date,runtime,popularity,vote_average,vote_count,cast,crew,director
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",en,"In the 22nd century, a paraplegic Marine is di...","[Ingenious Film Partners, Twentieth Century Fo...",2009-12-10,162.0,150.437577,7.2,11800,"[{'character': 'Jake Sully', 'name': 'Sam Wort...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",en,"Captain Barbossa, long believed to be dead, ha...","[Walt Disney Pictures, Jerry Bruckheimer Films...",2007-05-19,169.0,139.082615,6.9,4500,"[{'character': 'Captain Jack Sparrow', 'name':...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",en,A cryptic message from Bond’s past sends him o...,"[Columbia Pictures, Danjaq, B24]",2015-10-26,148.0,107.376788,6.3,4466,"[{'character': 'James Bond', 'name': 'Daniel C...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",en,Following the death of District Attorney Harve...,"[Legendary Pictures, Warner Bros., DC Entertai...",2012-07-16,165.0,112.312950,7.6,9106,"[{'character': 'Bruce Wayne / Batman', 'name':...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",en,"John Carter is a war-weary, former military ca...",[Walt Disney Pictures],2012-03-07,132.0,43.926995,6.1,2124,"[{'character': 'John Carter', 'name': 'Taylor ...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",[Andrew Stanton]

In [ ]:
tmdb = tmdb.drop(columns=['crew'])

In [ ]:
tmdb = tmdb.rename(columns={"title_x": "title"})

In [ ]:
cols = ["genres", "keywords","production_companies","cast", "director"]

for col in cols:
    tmdb[col] = tmdb[col].apply(lambda x: np.nan if x == [] else x)

In [ ]:
tmdb[cols].isnull().sum()

genres                   27
keywords                410
production_companies    349
cast                     41
director                 29
dtype: int64

In [ ]:
tmdb = tmdb.dropna(subset=["genres","cast", "director"])

In [ ]:
tmdb.isnull().sum()

movie_id                  0
title                     0
genres                    0
keywords                363
original_language         0
overview                  0
production_companies    300
release_date              0
runtime                   0
popularity                0
vote_average              0
vote_count                0
cast                      0
director                  0
dtype: int64

I did not remove the `keywords` and `production_companies` features because it contains a large number of values (around 400+ missing entries), and removing or reprocessing it would be **costly**, while it is also not a critical feature for content-based filtering compared to other attributes like genres or cast

### **- Convert back to empty list to ensure consistency after api extraction and merged dataset**

In [ ]:
tmdb.loc[:, 'keywords'] = tmdb['keywords'].apply(lambda x: x if isinstance(x, list) else [])
tmdb.loc[:, 'production_companies'] = tmdb['production_companies'].apply(lambda x: x if isinstance(x, list) else [])

In [ ]:
tmdb.isnull().sum()

movie_id                0
title                   0
genres                  0
keywords                0
original_language       0
overview                0
production_companies    0
release_date            0
runtime                 0
popularity              0
vote_average            0
vote_count              0
cast                    0
director                0
dtype: int64

## **Combined Dataset**
- TMDB Dataset: Add media type and source columns
- Missing_movies datset : Add source columns

### **- Find how many movies are missing at tmdb dataset (Based on movieLens movie)**

In [ ]:
# TMDB Movie
tmdb_ids = set(tmdb['movie_id'])

# MovieLens Movie
ml_ids = set(movieLens['tmdbId'])

missing_tmdb_ids = ml_ids - tmdb_ids

# Movies that does not have deeper information
missing_movies = movieLens[movieLens['tmdbId'].isin(missing_tmdb_ids)]

In [ ]:
missing_movies.head()

,movieId,title,genres,imdbId,tmdbId,media_type
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,8844,movie
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,15602,movie
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,31357,movie
4,5,Father of the Bride Part II (1995),Comedy,113041,11862,movie
5,6,Heat (1995),Action|Crime|Thriller,113277,949,movie

In [ ]:
print(missing_movies.isna().sum())
print(missing_movies.shape)

movieId       0
title         0
genres        0
imdbId        0
tmdbId        0
media_type    0
dtype: int64
(6198, 6)

Here have around 6200 movies that have been rated by users, but does not have deeper information (such as cast, character, popularity, release date and so on)

So that, I combined the `TMDB 5000 dataset` from **Kaggle** with `MovieLens user-rated movies` that were missing from the TMDB 5000 dataset (**missing_movies dataframe)**, allowing missing movie information to be retrieved through the TMDB API more efficiently.

In [ ]:
missing_movies = missing_movies.drop(columns=['movieId','title','genres','imdbId'])
missing_movies["source"] = "movielens"

In [ ]:
tmdb['media_type'] = 'movie'
tmdb['source'] = 'kaggle'

In [ ]:
print(tmdb.shape)
print(missing_movies.shape)

(4738, 16)
(6198, 3)

In [ ]:
tmdb = tmdb.rename(columns={"movie_id":"tmdbId"})
combined_df = pd.concat([tmdb, missing_movies], ignore_index=True)

In [ ]:
combined_df.shape

(10936, 16)

In [ ]:
combine_duplicate = combined_df[combined_df.duplicated(subset=['tmdbId','media_type'],keep=False)]
combine_duplicate

Empty DataFrame
Columns: [tmdbId, title, genres, keywords, original_language, overview, production_companies, release_date, runtime, popularity, vote_average, vote_count, cast, director, media_type, source]
Index: []

In [ ]:
combined_df.head()

,tmdbId,title,genres,keywords,original_language,overview,production_companies,release_date,runtime,popularity,vote_average,vote_count,cast,director,media_type,source
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",en,"In the 22nd century, a paraplegic Marine is di...","[Ingenious Film Partners, Twentieth Century Fo...",2009-12-10,162.0,150.437577,7.2,11800.0,"[{'character': 'Jake Sully', 'name': 'Sam Wort...",[James Cameron],movie,kaggle
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",en,"Captain Barbossa, long believed to be dead, ha...","[Walt Disney Pictures, Jerry Bruckheimer Films...",2007-05-19,169.0,139.082615,6.9,4500.0,"[{'character': 'Captain Jack Sparrow', 'name':...",[Gore Verbinski],movie,kaggle
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",en,A cryptic message from Bond’s past sends him o...,"[Columbia Pictures, Danjaq, B24]",2015-10-26,148.0,107.376788,6.3,4466.0,"[{'character': 'James Bond', 'name': 'Daniel C...",[Sam Mendes],movie,kaggle
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",en,Following the death of District Attorney Harve...,"[Legendary Pictures, Warner Bros., DC Entertai...",2012-07-16,165.0,112.312950,7.6,9106.0,"[{'character': 'Bruce Wayne / Batman', 'name':...",[Christopher Nolan],movie,kaggle
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",en,"John Carter is a war-weary, former military ca...",[Walt Disney Pictures],2012-03-07,132.0,43.926995,6.1,2124.0,"[{'character': 'John Carter', 'name': 'Taylor ...",[Andrew Stanton],movie,kaggle

I have add a new column called `source` for both datasets to improve the efficiency of the API extraction process. This column is used to distinguish between records originating from the Kaggle TMDB dataset and those from the MovieLens dataset.

- The **Kaggle** dataset already contains most of the required movie metadata, except for poster-related information, whereas the **MovieLens** dataset lacks nearly all detailed movie information.

By introducing the `source` column, the data processing pipeline can apply different extraction strategies: **lightweight API calls for Kaggle records to retrieve only poster data**, and **full metadata enrichment via the API for MovieLens records**. This separation helps optimize API usage, reduce unnecessary requests, and improve overall processing efficiency.

## **API**

### **Extraction Using API KEY**

In [ ]:
from tqdm import tqdm  #customizable progress bars to loops

# =========================================================
# CONFIG
# =========================================================
API_KEY = "API_KEY"
CACHE_FILE = "/content/drive/MyDrive/dataset/movie/API/tmdb_cache1.json"
BASE_URL = "https://api.themoviedb.org/3"
RATE_LIMIT_SLEEP = 0.25

# =========================================================
# LOAD CACHE
# =========================================================
try:
    with open(CACHE_FILE, "r") as f:
        cache = json.load(f)

except FileNotFoundError:
    cache = {}

print(f"✅ Loaded cache items: {len(cache)}")

✅ Loaded cache items: 0

In [ ]:
# 2 Functions : request_json and build_tmdb_response

# =========================================================
# SAFE REQUEST
# =========================================================
def request_json(url):
    try:
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            return response.json()
        return None
    except Exception:
        return None

# =========================================================
# EXTRACT MOVIE OR TV
# =========================================================
def build_tmdb_response(details, media_type):
        credits = details.get("credits", {})
        keywords = details.get("keywords", {})

        # TV uses "name" instead of "title"
        title = (
            details.get("title")
            if media_type == "movie"
            else details.get("name")
        )
        # TV uses "first_air_date"
        release_date = (
            details.get("release_date")
            if media_type == "movie"
            else details.get("first_air_date")
        )
        # TV uses episode runtime list
        runtime = (
            details.get("runtime")
            if media_type == "movie"
            else (
                details.get("episode_run_time", [None])[0]
                if details.get("episode_run_time")
                else None
            )
        )
        # keyword structure differs
        keyword_source = (
            keywords.get("keywords", [])
            if media_type == "movie"
            else keywords.get("results", [])
        )
        keyword_list = [
            k.get("name")
            for k in keyword_source
            if k.get("name")
        ]
        # Poster related
        poster_path = details.get("poster_path")

        # Return Values
        return {
            "tmdbId": details.get("id"),
            "media_type": media_type,
            "title": title,

            "genres": [
                g.get("name")
                for g in details.get("genres", [])
                if g.get("name")
            ],

            "keywords": keyword_list,
            "original_language": details.get("original_language"),
            "overview": details.get("overview"),

            "production_companies": [
                p.get("name")
                for p in details.get("production_companies", [])
                if p.get("name")
            ],

            "release_date": release_date,
            "runtime": runtime,
            "popularity": details.get("popularity"),
            "vote_average": details.get("vote_average"),
            "vote_count": details.get("vote_count"),

            "cast": [
                {
                    "character": c.get("character") if c.get("character") else "Unknown Character",
                    "actor": c.get("name") if c.get("name") else "Unknown Actor"
                }
                for c in credits.get("cast", [])
                if c.get("name") or c.get("character")
            ],

            "director": [
                c.get("name")
                for c in credits.get("crew", [])
                if c.get("job") == "Director" and c.get("name")
            ],

            "poster_path": poster_path,

            "poster_url": (
                f"https://image.tmdb.org/t/p/w500{poster_path}"
                if poster_path
                else None
            )
        }

In [ ]:
# =========================================================
#  A) KAGGLE
# =========================================================
# GET POSTER only
def fetch_tmdb_poster(tmdb_id, media_type):
    try:
        url = f"{BASE_URL}/{media_type}/{tmdb_id}?api_key={API_KEY}"
        details = request_json(url)

        if details is None:
            return None

        poster_path = details.get("poster_path")

        return {
            "poster_path": poster_path,
            "poster_url": (
                f"https://image.tmdb.org/t/p/w500{poster_path}"
                if poster_path
                else None
            )
        }

    except Exception as e:
        print(f"❌ Poster error {tmdb_id}: {e}")
        return None

# =========================================================
#  B) MOVIELENS
# =========================================================

# GET MOVIE
def fetch_tmdb_movie(tmdb_id):
    try:
        url = (
            f"{BASE_URL}/movie/{tmdb_id}"
            f"?api_key={API_KEY}"
            f"&append_to_response=credits,keywords"
        )
        details = request_json(url)
        if details is None:
            return None

        return build_tmdb_response(details, "movie")

    except Exception as e:
        print(f"❌ Movie error {tmdb_id}: {e}")
        return None

# GET TV
def fetch_tmdb_tv(tmdb_id):
    try:
        url = (
            f"{BASE_URL}/tv/{tmdb_id}"
            f"?api_key={API_KEY}"
            f"&append_to_response=credits,keywords"
        )
        details = request_json(url)
        if details is None:
            return None

        return build_tmdb_response(details, "tv")

    except Exception as e:
        print(f"❌ TV error {tmdb_id}: {e}")
        return None

In [ ]:
import json
import time
import math
import pandas as pd
import numpy as np
from tqdm import tqdm

STATUS_SUCCESS = "success"
STATUS_FAIL = "failed"

# -----------------------------
# SAFE blank checker
# -----------------------------
def is_blank(v):
    if v is None:
        return True

    # numpy array / list
    if isinstance(v, (list, tuple, np.ndarray)):
        return len(v) == 0

    # pandas / numpy NaN
    try:
        if pd.isna(v):
            return True
    except:
        pass

    return v == ""


# -----------------------------
# CLEAN pandas row → python safe
# -----------------------------
def clean_row(d):
    cleaned = {}

    for k, v in d.items():

        # convert numpy arrays → list
        if isinstance(v, np.ndarray):
            v = v.tolist()

        # convert NaN → None
        try:
            if pd.isna(v):
                v = None
        except:
            pass

        cleaned[k] = v

    return cleaned


# =========================================================
# MAIN FUNCTION
# =========================================================
def extract_tmdb_data(df, cache):

    df = df.copy()
    rows = df.dropna(subset=["tmdbId"])

    # ---------------------------------
    # CACHE INIT
    # ---------------------------------
    cache.setdefault("tmdb_cache", {})
    tmdb_cache = cache["tmdb_cache"]

    api_results = []

    # ---------------------------------
    # LOOP
    # ---------------------------------
    for idx, row in enumerate(
        tqdm(rows.itertuples(index=False), total=len(rows)),
        start=1
    ):

        tmdb_id = str(int(row.tmdbId))
        media_type = row.media_type
        source = row.source

        cache_key = f"{media_type}_{tmdb_id}"

        data = None
        poster_status = None
        status = None

        # =====================================================
        # CACHE CHECK
        # =====================================================
        cached = tmdb_cache.get(cache_key)

        if cached:
            if cached.get("status") == STATUS_FAIL:
                continue

            data = cached.get("data")
            poster_status = cached.get("poster_status")
            status = cached.get("status")

        # =====================================================
        # FETCH
        # =====================================================
        if data is None:

            try:

                # -----------------------------
                # KAGGLE
                # -----------------------------
                if source == "kaggle":

                    base_data = clean_row(row._asdict())

                    poster_data = fetch_tmdb_poster(tmdb_id, media_type) or {}
                    poster_data = clean_row(poster_data)

                    data = {
                        **base_data,
                        **poster_data
                    }

                    poster_path = poster_data.get("poster_path")
                    poster_url = poster_data.get("poster_url")

                    poster_status = (
                        STATUS_SUCCESS
                        if not is_blank(poster_path)
                        and not is_blank(poster_url)
                        else STATUS_FAIL
                    )

                    status = (
                        STATUS_SUCCESS
                        if poster_status == STATUS_SUCCESS
                        else STATUS_FAIL
                    )

                # -----------------------------
                # MOVIELENS
                # -----------------------------
                else:

                    if media_type == "movie":
                        data = fetch_tmdb_movie(tmdb_id)

                    elif media_type == "tv":
                        data = fetch_tmdb_tv(tmdb_id)

                    data = clean_row(data) if data else None

                    status = (
                        STATUS_SUCCESS
                        if data
                        else STATUS_FAIL
                    )

            except Exception as e:

                print(f"❌ Error {cache_key}: {e}")

                if source == "kaggle":
                    data = clean_row(row._asdict())
                    poster_status = STATUS_FAIL
                    status = STATUS_FAIL
                else:
                    data = None
                    status = STATUS_FAIL

            # =====================================================
            # CACHE SAVE
            # =====================================================
            tmdb_cache[cache_key] = {
                "status": status,
                "poster_status": poster_status,
                "data": data
            }

            time.sleep(RATE_LIMIT_SLEEP)

        # =====================================================
        # OUTPUT
        # =====================================================
        if data:

            result_item = {
                "cache_key": cache_key,
                "status": status,
                "poster_status": poster_status,
                "media_type": media_type,
                "source": source,
                "tmdbId": tmdb_id,
                **data
            }

        else:

            result_item = {
                "cache_key": cache_key,
                "status": STATUS_FAIL,
                "poster_status": poster_status,
                "media_type": media_type,
                "source": source,
                "tmdbId": tmdb_id,
                "title": None,
                "overview": None,
                "cast": []
            }

        api_results.append(result_item)

        # periodic save
        if idx % 50 == 0:
            with open(CACHE_FILE, "w") as f:
                json.dump(cache, f)

            print(f"💾 Saved | cache={len(tmdb_cache)}")

    # final save
    with open(CACHE_FILE, "w") as f:
        json.dump(cache, f)

    print("\n✅ DONE")
    print(f"Results: {len(api_results)}")
    print(f"Cache size: {len(tmdb_cache)}")

    return api_results

In [ ]:
api_results = extract_tmdb_data(combined_df, cache)

  0%|          | 50/10936 [00:16<1:00:20,  3.01it/s]

💾 Saved | cache=50

  1%|          | 71/10936 [00:22<57:01,  3.18it/s]/tmp/ipykernel_1287/2796670177.py:46: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if pd.isna(v):
  1%|          | 100/10936 [00:32<1:02:09,  2.91it/s]

💾 Saved | cache=100

  1%|▏         | 150/10936 [00:48<1:00:03,  2.99it/s]

💾 Saved | cache=150

  2%|▏         | 200/10936 [01:04<1:02:30,  2.86it/s]

💾 Saved | cache=200

  2%|▏         | 250/10936 [01:20<1:00:05,  2.96it/s]

💾 Saved | cache=250

  3%|▎         | 300/10936 [01:36<1:00:39,  2.92it/s]

💾 Saved | cache=300

  3%|▎         | 350/10936 [01:52<1:02:20,  2.83it/s]

💾 Saved | cache=350

  4%|▎         | 400/10936 [02:08<1:01:43,  2.85it/s]

💾 Saved | cache=400

  4%|▍         | 450/10936 [02:24<1:04:45,  2.70it/s]

💾 Saved | cache=450

  5%|▍         | 500/10936 [02:40<1:05:22,  2.66it/s]

💾 Saved | cache=500

  5%|▌         | 550/10936 [02:56<1:02:35,  2.77it/s]

💾 Saved | cache=550

  5%|▌         | 600/10936 [03:12<1:00:55,  2.83it/s]

💾 Saved | cache=600

  6%|▌         | 650/10936 [03:29<1:01:49,  2.77it/s]

💾 Saved | cache=650

  6%|▋         | 700/10936 [03:45<1:01:46,  2.76it/s]

💾 Saved | cache=700

  7%|▋         | 750/10936 [04:01<1:07:24,  2.52it/s]

💾 Saved | cache=750

  7%|▋         | 800/10936 [04:17<1:02:56,  2.68it/s]

💾 Saved | cache=800

  8%|▊         | 850/10936 [04:33<1:02:21,  2.70it/s]

💾 Saved | cache=850

  8%|▊         | 900/10936 [04:49<1:03:28,  2.63it/s]

💾 Saved | cache=900

  9%|▊         | 950/10936 [05:05<1:02:15,  2.67it/s]

💾 Saved | cache=950

  9%|▉         | 1000/10936 [05:22<1:08:21,  2.42it/s]

💾 Saved | cache=1000

 10%|▉         | 1050/10936 [05:38<1:04:35,  2.55it/s]

💾 Saved | cache=1050

 10%|█         | 1100/10936 [05:54<1:02:51,  2.61it/s]

💾 Saved | cache=1100

 11%|█         | 1150/10936 [06:10<1:04:21,  2.53it/s]

💾 Saved | cache=1150

 11%|█         | 1200/10936 [06:27<1:04:19,  2.52it/s]

💾 Saved | cache=1200

 11%|█▏        | 1250/10936 [06:43<1:10:54,  2.28it/s]

💾 Saved | cache=1250

 12%|█▏        | 1300/10936 [06:59<1:05:32,  2.45it/s]

💾 Saved | cache=1300

 12%|█▏        | 1350/10936 [07:16<1:03:06,  2.53it/s]

💾 Saved | cache=1350

 13%|█▎        | 1400/10936 [07:32<1:05:16,  2.43it/s]

💾 Saved | cache=1400

 13%|█▎        | 1450/10936 [07:48<1:04:53,  2.44it/s]

💾 Saved | cache=1450

 14%|█▎        | 1500/10936 [08:05<1:19:33,  1.98it/s]

💾 Saved | cache=1500

 14%|█▍        | 1550/10936 [08:24<1:13:16,  2.13it/s]

💾 Saved | cache=1550

 15%|█▍        | 1600/10936 [08:41<1:04:41,  2.41it/s]

💾 Saved | cache=1600

 15%|█▌        | 1650/10936 [08:57<1:03:41,  2.43it/s]

💾 Saved | cache=1650

 16%|█▌        | 1700/10936 [09:13<1:12:07,  2.13it/s]

💾 Saved | cache=1700

 16%|█▌        | 1750/10936 [09:30<1:03:35,  2.41it/s]

💾 Saved | cache=1750

 16%|█▋        | 1800/10936 [09:46<1:06:11,  2.30it/s]

💾 Saved | cache=1800

 17%|█▋        | 1850/10936 [10:03<1:03:45,  2.37it/s]

💾 Saved | cache=1850

 17%|█▋        | 1900/10936 [10:19<1:04:30,  2.33it/s]

💾 Saved | cache=1900

 18%|█▊        | 1950/10936 [10:36<1:14:07,  2.02it/s]

💾 Saved | cache=1950

 18%|█▊        | 2000/10936 [10:52<1:05:16,  2.28it/s]

💾 Saved | cache=2000

 19%|█▊        | 2050/10936 [11:08<1:06:30,  2.23it/s]

💾 Saved | cache=2050

 19%|█▉        | 2100/10936 [11:25<1:05:36,  2.24it/s]

💾 Saved | cache=2100

 20%|█▉        | 2150/10936 [11:41<1:12:31,  2.02it/s]

💾 Saved | cache=2150

 20%|██        | 2200/10936 [11:58<1:15:36,  1.93it/s]

💾 Saved | cache=2200

 21%|██        | 2250/10936 [12:14<1:05:04,  2.22it/s]

💾 Saved | cache=2250

 21%|██        | 2300/10936 [12:31<1:04:53,  2.22it/s]

💾 Saved | cache=2300

 21%|██▏       | 2350/10936 [12:47<1:03:56,  2.24it/s]

💾 Saved | cache=2350

 22%|██▏       | 2400/10936 [13:04<1:16:04,  1.87it/s]

💾 Saved | cache=2400

 22%|██▏       | 2450/10936 [13:20<1:04:30,  2.19it/s]

💾 Saved | cache=2450

 23%|██▎       | 2500/10936 [13:37<1:05:37,  2.14it/s]

💾 Saved | cache=2500

 23%|██▎       | 2550/10936 [13:54<1:04:04,  2.18it/s]

💾 Saved | cache=2550

 24%|██▍       | 2600/10936 [14:10<1:04:59,  2.14it/s]

💾 Saved | cache=2600

 24%|██▍       | 2650/10936 [14:27<1:18:05,  1.77it/s]

💾 Saved | cache=2650

 25%|██▍       | 2700/10936 [14:43<1:03:40,  2.16it/s]

💾 Saved | cache=2700

 25%|██▌       | 2750/10936 [15:00<1:05:31,  2.08it/s]

💾 Saved | cache=2750

 26%|██▌       | 2800/10936 [15:16<1:04:52,  2.09it/s]

💾 Saved | cache=2800

 26%|██▌       | 2850/10936 [15:33<1:14:35,  1.81it/s]

💾 Saved | cache=2850

 27%|██▋       | 2900/10936 [15:50<1:15:25,  1.78it/s]

💾 Saved | cache=2900

 27%|██▋       | 2950/10936 [16:06<1:02:20,  2.14it/s]

💾 Saved | cache=2950

 27%|██▋       | 3000/10936 [16:23<1:01:55,  2.14it/s]

💾 Saved | cache=3000

 28%|██▊       | 3050/10936 [16:39<1:05:54,  1.99it/s]

💾 Saved | cache=3050

 28%|██▊       | 3100/10936 [16:56<1:15:47,  1.72it/s]

💾 Saved | cache=3100

 29%|██▉       | 3150/10936 [17:13<1:02:24,  2.08it/s]

💾 Saved | cache=3150

 29%|██▉       | 3200/10936 [17:29<1:02:56,  2.05it/s]

💾 Saved | cache=3200

 30%|██▉       | 3250/10936 [17:46<1:02:58,  2.03it/s]

💾 Saved | cache=3250

 30%|███       | 3300/10936 [18:02<1:03:11,  2.01it/s]

💾 Saved | cache=3300

 31%|███       | 3350/10936 [18:19<1:15:27,  1.68it/s]

💾 Saved | cache=3350

 31%|███       | 3400/10936 [18:36<1:02:27,  2.01it/s]

💾 Saved | cache=3400

 32%|███▏      | 3450/10936 [18:52<1:02:46,  1.99it/s]

💾 Saved | cache=3450

 32%|███▏      | 3500/10936 [19:33<1:40:21,  1.24it/s]

💾 Saved | cache=3500

 32%|███▏      | 3550/10936 [19:50<1:01:54,  1.99it/s]

💾 Saved | cache=3550

 33%|███▎      | 3600/10936 [20:07<1:16:01,  1.61it/s]

💾 Saved | cache=3600

 33%|███▎      | 3650/10936 [20:24<1:01:44,  1.97it/s]

💾 Saved | cache=3650

 34%|███▍      | 3700/10936 [20:40<1:01:42,  1.95it/s]

💾 Saved | cache=3700

 34%|███▍      | 3750/10936 [20:57<1:00:56,  1.97it/s]

💾 Saved | cache=3750

 35%|███▍      | 3800/10936 [21:14<1:13:39,  1.61it/s]

💾 Saved | cache=3800

 35%|███▌      | 3850/10936 [21:31<1:08:01,  1.74it/s]

💾 Saved | cache=3850

 36%|███▌      | 3900/10936 [21:48<1:01:36,  1.90it/s]

💾 Saved | cache=3900

 36%|███▌      | 3950/10936 [22:05<1:03:42,  1.83it/s]

💾 Saved | cache=3950

 37%|███▋      | 4000/10936 [22:21<1:03:52,  1.81it/s]

💾 Saved | cache=4000

 37%|███▋      | 4050/10936 [22:39<1:12:03,  1.59it/s]

💾 Saved | cache=4050

 37%|███▋      | 4100/10936 [22:55<59:05,  1.93it/s]

💾 Saved | cache=4100

 38%|███▊      | 4150/10936 [23:12<1:00:06,  1.88it/s]

💾 Saved | cache=4150

 38%|███▊      | 4200/10936 [23:29<58:33,  1.92it/s]

💾 Saved | cache=4200

 39%|███▉      | 4250/10936 [23:46<1:12:42,  1.53it/s]

💾 Saved | cache=4250

 39%|███▉      | 4300/10936 [24:02<1:00:14,  1.84it/s]

💾 Saved | cache=4300

 40%|███▉      | 4350/10936 [24:19<56:59,  1.93it/s]

💾 Saved | cache=4350

 40%|████      | 4400/10936 [24:36<56:53,  1.91it/s]

💾 Saved | cache=4400

 41%|████      | 4450/10936 [24:53<1:12:11,  1.50it/s]

💾 Saved | cache=4450

 41%|████      | 4500/10936 [25:10<57:07,  1.88it/s]

💾 Saved | cache=4500

 42%|████▏     | 4550/10936 [25:26<55:45,  1.91it/s]

💾 Saved | cache=4550

 42%|████▏     | 4600/10936 [25:43<55:46,  1.89it/s]

💾 Saved | cache=4600

 43%|████▎     | 4650/10936 [25:59<55:45,  1.88it/s]

💾 Saved | cache=4650

 43%|████▎     | 4700/10936 [26:17<1:10:25,  1.48it/s]

💾 Saved | cache=4700

 43%|████▎     | 4750/10936 [26:33<55:15,  1.87it/s]

💾 Saved | cache=4750

 44%|████▍     | 4800/10936 [26:50<58:43,  1.74it/s]

💾 Saved | cache=4800

 44%|████▍     | 4850/10936 [27:08<56:55,  1.78it/s]

💾 Saved | cache=4850

 45%|████▍     | 4900/10936 [27:25<1:11:31,  1.41it/s]

💾 Saved | cache=4900

 45%|████▌     | 4950/10936 [27:42<55:39,  1.79it/s]

💾 Saved | cache=4950

 46%|████▌     | 5000/10936 [28:00<56:01,  1.77it/s]

💾 Saved | cache=5000

 46%|████▌     | 5050/10936 [28:17<1:10:28,  1.39it/s]

💾 Saved | cache=5050

 47%|████▋     | 5100/10936 [28:35<55:46,  1.74it/s]

💾 Saved | cache=5100

 47%|████▋     | 5150/10936 [28:52<54:06,  1.78it/s]

💾 Saved | cache=5150

 48%|████▊     | 5200/10936 [29:09<56:29,  1.69it/s]

💾 Saved | cache=5200

 48%|████▊     | 5250/10936 [29:27<1:11:29,  1.33it/s]

💾 Saved | cache=5250

 48%|████▊     | 5300/10936 [29:44<54:10,  1.73it/s]

💾 Saved | cache=5300

 49%|████▉     | 5350/10936 [30:01<53:05,  1.75it/s]

💾 Saved | cache=5350

 49%|████▉     | 5400/10936 [30:18<53:43,  1.72it/s]

💾 Saved | cache=5400

 50%|████▉     | 5450/10936 [30:36<1:10:27,  1.30it/s]

💾 Saved | cache=5450

 50%|█████     | 5500/10936 [30:56<59:08,  1.53it/s]

💾 Saved | cache=5500

 51%|█████     | 5550/10936 [31:14<1:04:53,  1.38it/s]

💾 Saved | cache=5550

 51%|█████     | 5600/10936 [31:31<58:07,  1.53it/s]

💾 Saved | cache=5600

 52%|█████▏    | 5650/10936 [31:51<56:40,  1.55it/s]

💾 Saved | cache=5650

 52%|█████▏    | 5700/10936 [32:10<1:08:46,  1.27it/s]

💾 Saved | cache=5700

 53%|█████▎    | 5750/10936 [32:27<55:31,  1.56it/s]

💾 Saved | cache=5750

 53%|█████▎    | 5800/10936 [32:45<53:14,  1.61it/s]

💾 Saved | cache=5800

 53%|█████▎    | 5850/10936 [33:02<52:55,  1.60it/s]

💾 Saved | cache=5850

 54%|█████▍    | 5900/10936 [33:20<1:07:21,  1.25it/s]

💾 Saved | cache=5900

 54%|█████▍    | 5950/10936 [33:37<51:40,  1.61it/s]

💾 Saved | cache=5950

 55%|█████▍    | 6000/10936 [33:54<50:30,  1.63it/s]

💾 Saved | cache=6000

 55%|█████▌    | 6050/10936 [34:12<1:06:46,  1.22it/s]

💾 Saved | cache=6050

 56%|█████▌    | 6100/10936 [34:30<50:15,  1.60it/s]

💾 Saved | cache=6100

 56%|█████▌    | 6150/10936 [34:47<52:04,  1.53it/s]

💾 Saved | cache=6150

 57%|█████▋    | 6200/10936 [35:05<51:25,  1.53it/s]

💾 Saved | cache=6200

 57%|█████▋    | 6250/10936 [35:23<1:06:45,  1.17it/s]

💾 Saved | cache=6250

 58%|█████▊    | 6300/10936 [35:42<50:18,  1.54it/s]

💾 Saved | cache=6300

 58%|█████▊    | 6350/10936 [36:00<50:53,  1.50it/s]

💾 Saved | cache=6350

 59%|█████▊    | 6400/10936 [36:18<1:06:06,  1.14it/s]

💾 Saved | cache=6400

 59%|█████▉    | 6450/10936 [36:36<49:52,  1.50it/s]

💾 Saved | cache=6450

 59%|█████▉    | 6500/10936 [36:53<49:33,  1.49it/s]

💾 Saved | cache=6500

 60%|█████▉    | 6550/10936 [37:11<1:03:21,  1.15it/s]

💾 Saved | cache=6550

 60%|██████    | 6600/10936 [37:29<47:00,  1.54it/s]

💾 Saved | cache=6600

 61%|██████    | 6650/10936 [37:46<47:44,  1.50it/s]

💾 Saved | cache=6650

 61%|██████▏   | 6700/10936 [38:04<48:08,  1.47it/s]

💾 Saved | cache=6700

 62%|██████▏   | 6750/10936 [38:22<58:04,  1.20it/s]

💾 Saved | cache=6750

 62%|██████▏   | 6800/10936 [38:39<45:44,  1.51it/s]

💾 Saved | cache=6800

 63%|██████▎   | 6850/10936 [38:57<45:48,  1.49it/s]

💾 Saved | cache=6850

 63%|██████▎   | 6900/10936 [39:15<1:00:00,  1.12it/s]

💾 Saved | cache=6900

 64%|██████▎   | 6950/10936 [39:32<44:57,  1.48it/s]

💾 Saved | cache=6950

 64%|██████▍   | 7000/10936 [39:50<45:22,  1.45it/s]

💾 Saved | cache=7000

 64%|██████▍   | 7050/10936 [40:08<47:25,  1.37it/s]

💾 Saved | cache=7050

 65%|██████▍   | 7100/10936 [40:25<47:41,  1.34it/s]

💾 Saved | cache=7100

 65%|██████▌   | 7150/10936 [40:43<43:24,  1.45it/s]

💾 Saved | cache=7150

 66%|██████▌   | 7200/10936 [41:00<43:45,  1.42it/s]

💾 Saved | cache=7200

 66%|██████▋   | 7250/10936 [41:19<58:16,  1.05it/s]

💾 Saved | cache=7250

 67%|██████▋   | 7300/10936 [41:36<43:56,  1.38it/s]

💾 Saved | cache=7300

 67%|██████▋   | 7350/10936 [41:54<41:51,  1.43it/s]

💾 Saved | cache=7350

 68%|██████▊   | 7400/10936 [42:13<55:34,  1.06it/s]

💾 Saved | cache=7400

 68%|██████▊   | 7450/10936 [42:30<41:08,  1.41it/s]

💾 Saved | cache=7450

 69%|██████▊   | 7500/10936 [42:48<41:02,  1.40it/s]

💾 Saved | cache=7500

 69%|██████▉   | 7550/10936 [43:06<46:43,  1.21it/s]

💾 Saved | cache=7550

 69%|██████▉   | 7600/10936 [43:24<41:39,  1.33it/s]

💾 Saved | cache=7600

 70%|██████▉   | 7650/10936 [43:42<41:06,  1.33it/s]

💾 Saved | cache=7650

 70%|███████   | 7700/10936 [44:00<40:15,  1.34it/s]

💾 Saved | cache=7700

 71%|███████   | 7750/10936 [44:18<45:53,  1.16it/s]

💾 Saved | cache=7750

 71%|███████▏  | 7800/10936 [44:35<38:27,  1.36it/s]

💾 Saved | cache=7800

 72%|███████▏  | 7850/10936 [44:53<37:46,  1.36it/s]

💾 Saved | cache=7850

 72%|███████▏  | 7900/10936 [45:12<50:47,  1.00s/it]

💾 Saved | cache=7900

 73%|███████▎  | 7950/10936 [45:29<36:31,  1.36it/s]

💾 Saved | cache=7950

 73%|███████▎  | 8000/10936 [45:47<36:26,  1.34it/s]

💾 Saved | cache=8000

 74%|███████▎  | 8050/10936 [46:06<49:10,  1.02s/it]

💾 Saved | cache=8050

 74%|███████▍  | 8100/10936 [46:23<35:12,  1.34it/s]

💾 Saved | cache=8100

 75%|███████▍  | 8150/10936 [46:41<34:36,  1.34it/s]

💾 Saved | cache=8150

 75%|███████▍  | 8200/10936 [46:59<37:18,  1.22it/s]

💾 Saved | cache=8200

 75%|███████▌  | 8250/10936 [47:17<37:28,  1.19it/s]

💾 Saved | cache=8250

 76%|███████▌  | 8300/10936 [47:35<33:42,  1.30it/s]

💾 Saved | cache=8300

 76%|███████▋  | 8350/10936 [47:52<32:10,  1.34it/s]

💾 Saved | cache=8350

 77%|███████▋  | 8400/10936 [48:11<41:49,  1.01it/s]

💾 Saved | cache=8400

 77%|███████▋  | 8450/10936 [48:29<31:55,  1.30it/s]

💾 Saved | cache=8450

 78%|███████▊  | 8500/10936 [48:47<32:36,  1.24it/s]

💾 Saved | cache=8500

 78%|███████▊  | 8550/10936 [49:06<43:16,  1.09s/it]

💾 Saved | cache=8550

 79%|███████▊  | 8600/10936 [49:23<29:39,  1.31it/s]

💾 Saved | cache=8600

 79%|███████▉  | 8650/10936 [49:41<30:44,  1.24it/s]

💾 Saved | cache=8650

 80%|███████▉  | 8700/10936 [50:00<40:31,  1.09s/it]

💾 Saved | cache=8700

 80%|████████  | 8750/10936 [50:18<28:59,  1.26it/s]

💾 Saved | cache=8750

 80%|████████  | 8800/10936 [50:36<27:25,  1.30it/s]

💾 Saved | cache=8800

 81%|████████  | 8850/10936 [50:55<37:27,  1.08s/it]

💾 Saved | cache=8850

 81%|████████▏ | 8900/10936 [51:12<27:28,  1.24it/s]

💾 Saved | cache=8900

 82%|████████▏ | 8950/10936 [51:30<26:01,  1.27it/s]

💾 Saved | cache=8950

 82%|████████▏ | 9000/10936 [51:49<30:52,  1.04it/s]

💾 Saved | cache=9000

 83%|████████▎ | 9050/10936 [52:07<25:48,  1.22it/s]

💾 Saved | cache=9050

 83%|████████▎ | 9100/10936 [52:25<24:19,  1.26it/s]

💾 Saved | cache=9100

 84%|████████▎ | 9150/10936 [52:43<30:12,  1.01s/it]

💾 Saved | cache=9150

 84%|████████▍ | 9200/10936 [53:01<23:27,  1.23it/s]

💾 Saved | cache=9200

 85%|████████▍ | 9250/10936 [53:19<22:35,  1.24it/s]

💾 Saved | cache=9250

 85%|████████▌ | 9300/10936 [53:38<25:00,  1.09it/s]

💾 Saved | cache=9300

 85%|████████▌ | 9350/10936 [53:56<22:28,  1.18it/s]

💾 Saved | cache=9350

 86%|████████▌ | 9400/10936 [54:14<21:43,  1.18it/s]

💾 Saved | cache=9400

 86%|████████▋ | 9450/10936 [54:32<22:01,  1.12it/s]

💾 Saved | cache=9450

 87%|████████▋ | 9500/10936 [54:50<21:45,  1.10it/s]

💾 Saved | cache=9500

 87%|████████▋ | 9550/10936 [55:08<19:14,  1.20it/s]

💾 Saved | cache=9550

 88%|████████▊ | 9600/10936 [55:26<18:18,  1.22it/s]

💾 Saved | cache=9600

 88%|████████▊ | 9650/10936 [55:45<20:40,  1.04it/s]

💾 Saved | cache=9650

 89%|████████▊ | 9700/10936 [56:02<17:13,  1.20it/s]

💾 Saved | cache=9700

 89%|████████▉ | 9750/10936 [56:21<16:37,  1.19it/s]

💾 Saved | cache=9750

 90%|████████▉ | 9800/10936 [56:39<18:24,  1.03it/s]

💾 Saved | cache=9800

 90%|█████████ | 9850/10936 [56:57<15:32,  1.16it/s]

💾 Saved | cache=9850

 91%|█████████ | 9900/10936 [57:15<14:55,  1.16it/s]

💾 Saved | cache=9900

 91%|█████████ | 9950/10936 [57:34<16:12,  1.01it/s]

💾 Saved | cache=9950

 91%|█████████▏| 10000/10936 [57:52<13:30,  1.15it/s]

💾 Saved | cache=10000

 92%|█████████▏| 10050/10936 [58:10<13:49,  1.07it/s]

💾 Saved | cache=10050

 92%|█████████▏| 10100/10936 [58:28<12:59,  1.07it/s]

💾 Saved | cache=10100

 93%|█████████▎| 10150/10936 [58:47<11:23,  1.15it/s]

💾 Saved | cache=10150

 93%|█████████▎| 10200/10936 [59:05<11:26,  1.07it/s]

💾 Saved | cache=10200

 94%|█████████▎| 10250/10936 [59:25<10:04,  1.13it/s]

💾 Saved | cache=10250

 94%|█████████▍| 10300/10936 [59:43<09:25,  1.13it/s]

💾 Saved | cache=10300

 95%|█████████▍| 10350/10936 [1:00:03<11:49,  1.21s/it]

💾 Saved | cache=10350

 95%|█████████▌| 10400/10936 [1:00:21<07:49,  1.14it/s]

💾 Saved | cache=10400

 96%|█████████▌| 10450/10936 [1:00:39<06:57,  1.16it/s]

💾 Saved | cache=10450

 96%|█████████▌| 10500/10936 [1:00:59<09:04,  1.25s/it]

💾 Saved | cache=10500

 96%|█████████▋| 10550/10936 [1:01:17<05:38,  1.14it/s]

💾 Saved | cache=10550

 97%|█████████▋| 10600/10936 [1:01:35<04:59,  1.12it/s]

💾 Saved | cache=10600

 97%|█████████▋| 10650/10936 [1:01:54<05:18,  1.11s/it]

💾 Saved | cache=10650

 98%|█████████▊| 10700/10936 [1:02:12<03:33,  1.11it/s]

💾 Saved | cache=10700

 98%|█████████▊| 10750/10936 [1:02:31<02:48,  1.10it/s]

💾 Saved | cache=10750

 99%|█████████▉| 10800/10936 [1:02:49<02:20,  1.03s/it]

💾 Saved | cache=10800

 99%|█████████▉| 10850/10936 [1:03:07<01:15,  1.14it/s]

💾 Saved | cache=10850

100%|█████████▉| 10900/10936 [1:03:26<00:33,  1.06it/s]

💾 Saved | cache=10900

100%|██████████| 10936/10936 [1:03:38<00:00,  2.86it/s]

✅ DONE
Results: 10936
Cache size: 10936

### **Metrics Check**

#### - Failed Cache Keys Check

This function retrieves the cache keys of movies that failed the API extraction process, allowing us to identify IDs that may have been removed or deleted from the website.

In [ ]:
# =========================================================
# FAILED CACHE KEYS
# =========================================================
def get_failed_cache_keys(cache):
    tmdb_cache = cache.get("tmdb_cache", {})
    failed = [
        k for k, v in tmdb_cache.items()
        if v.get("status") == STATUS_FAIL
    ]
    print("❌ FAILED CACHE KEYS")
    print(f"Total failed: {len(failed)}")
    return failed

In [ ]:
get_failed_cache_keys(cache)

❌ FAILED CACHE KEYS
Total failed: 31

['movie_82525',
 'movie_10398',
 'movie_310706',
 'movie_112430',
 'movie_333355',
 'movie_153397',
 'movie_36597',
 'movie_183894',
 'movie_11042',
 'movie_395766',
 'movie_50942',
 'movie_364083',
 'movie_299553',
 'movie_146882',
 'movie_146269',
 'movie_181940',
 'movie_274758',
 'movie_361398',
 'movie_266857',
 'movie_215993',
 'movie_12224',
 'movie_54507',
 'movie_59017',
 'movie_202043',
 'movie_263947',
 'movie_215999',
 'movie_120605',
 'movie_327029',
 'movie_185789',
 'movie_65595',
 'movie_412103']

#### - Cache Report

This function generates a comprehensive cache report by counting total keys and categorizing them into successful, failed, or missing data status.

In [ ]:
# =========================================================
# CACHE HEALTH REPORT
# =========================================================
def cache_report(cache):
    tmdb_cache = cache.get("tmdb_cache", {})

    total = len(tmdb_cache)
    success = 0
    failed = 0
    missing = 0

    for v in tmdb_cache.values():
        if v.get("status") == STATUS_FAIL:
            failed += 1
        elif v.get("data") is None:
            missing += 1
        else:
            success += 1

    print("\n📊 CACHE REPORT")
    print(f"Total keys   : {total}")
    print(f"Success      : {success}")
    print(f"Failed       : {failed}")
    print(f"Missing data : {missing}")

    return {
        "total": total,
        "success": success,
        "failed": failed,
        "missing": missing
    }

In [ ]:
cache_report(cache)

📊 CACHE REPORT
Total keys   : 10936
Success      : 10905
Failed       : 31
Missing data : 0

{'total': 10936, 'success': 10905, 'failed': 31, 'missing': 0}

### **Full extraction Dataframe**

In [ ]:
final_tmdb_df = pd.DataFrame(api_results)
display(final_tmdb_df.head())

print(final_tmdb_df.shape)

,cache_key,status,poster_status,media_type,source,tmdbId,title,genres,keywords,original_language,...,production_companies,release_date,runtime,popularity,vote_average,vote_count,cast,director,poster_path,poster_url
0,movie_19995,success,success,movie,kaggle,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",en,...,"[Ingenious Film Partners, Twentieth Century Fo...",2009-12-10,162.0,150.437577,7.2,11800.0,"[{'character': 'Jake Sully', 'name': 'Sam Wort...",[James Cameron],/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,https://image.tmdb.org/t/p/w500/gKY6q7SjCkAU6F...
1,movie_285,success,success,movie,kaggle,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",en,...,"[Walt Disney Pictures, Jerry Bruckheimer Films...",2007-05-19,169.0,139.082615,6.9,4500.0,"[{'character': 'Captain Jack Sparrow', 'name':...",[Gore Verbinski],/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg,https://image.tmdb.org/t/p/w500/jGWpG4YhpQwVmj...
2,movie_206647,success,success,movie,kaggle,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",en,...,"[Columbia Pictures, Danjaq, B24]",2015-10-26,148.0,107.376788,6.3,4466.0,"[{'character': 'James Bond', 'name': 'Daniel C...",[Sam Mendes],/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg,https://image.tmdb.org/t/p/w500/zj8ongFhtWNsVl...
3,movie_49026,success,success,movie,kaggle,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",en,...,"[Legendary Pictures, Warner Bros., DC Entertai...",2012-07-16,165.0,112.312950,7.6,9106.0,"[{'character': 'Bruce Wayne / Batman', 'name':...",[Christopher Nolan],/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg,https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BY...
4,movie_49529,success,success,movie,kaggle,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",en,...,[Walt Disney Pictures],2012-03-07,132.0,43.926995,6.1,2124.0,"[{'character': 'John Carter', 'name': 'Taylor ...",[Andrew Stanton],/lCxz1Yus07QCQQCb6I0Dr3Lmqpx.jpg,https://image.tmdb.org/t/p/w500/lCxz1Yus07QCQQ...

(10936, 21)

In [ ]:
final_tmdb_df.iloc[0]

cache_key                                                     movie_19995
status                                                            success
poster_status                                                     success
media_type                                                          movie
source                                                             kaggle
tmdbId                                                              19995
title                                                              Avatar
genres                      [Action, Adventure, Fantasy, Science Fiction]
keywords                [culture clash, future, space war, space colon...
original_language                                                      en
overview                In the 22nd century, a paraplegic Marine is di...
production_companies    [Ingenious Film Partners, Twentieth Century Fo...
release_date                                                   2009-12-10
runtime                                                             162.0
popularity                                                     150.437577
vote_average                                                          7.2
vote_count                                                        11800.0
cast                    [{'character': 'Jake Sully', 'name': 'Sam Wort...
director                                                  [James Cameron]
poster_path                              /gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg
poster_url              https://image.tmdb.org/t/p/w500/gKY6q7SjCkAU6F...
Name: 0, dtype: object

### **Save csv to Google Drive For Part B**

In [ ]:
final_tmdb_df.to_csv('/content/drive/MyDrive/dataset/movie/API/preprocess_dataset/final_tmdb_api.csv', index=False)

In [ ]:
ratings.to_csv('/content/drive/MyDrive/dataset/movie/API/preprocess_dataset/ratings.csv', index=False)

In [ ]:
movieLens.shape

(9739, 6)

In [ ]:
movieLens.to_csv('/content/drive/MyDrive/dataset/movie/API/preprocess_dataset/movieLens.csv', index=False)